name: template
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.6.1

  intl: ^0.20.2
  get_it: ^8.0.3
  dio: ^5.8.0
  flutter_dotenv: ^5.2.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  flutter_secure_storage: ^8.0.0
  go_router: ^14.8.1

  firebase_core: ^3.0.0
  firebase_auth: ^5.5.0
  google_sign_in: ^6.3.0

  firebase_storage: ^12.4.5
  image_picker: ^1.0.4
  path: ^1.8.3

  google_fonts: ^6.2.1

  lottie: ^2.7.0
  http: ^1.0.0
  http_parser: ^4.0.2
  cached_network_image: ^3.3.0
  web_socket_channel: ^2.4.0

  flutter_sound: ^9.2.13
  permission_handler: ^11.3.0
  audioplayers: ^5.2.1
  path_provider: ^2.1.1
  just_audio: ^0.9.34

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/images/
